### ISSUE TITLE
Could you provide the requirements or yaml file?

### ISSUE THREAD

**Issue by BenoitKAO** [aripakman/amortized_community_detection#1]
Thank you for your marvelous work.

However, I encounter the issue of the environment.
Like,
  File "/.../attentive_clustering_processes/acp/utils/graph_utils.py", line 3, in <module>
    from torch_geometric.data import Data as GeomData
ModuleNotFoundError: No module named 'torch_geometric'

Could you provide the requirements or yaml file?

Thank you again.

**Comment by BenoitKAO** [comment]
Although I solved this issue of the environment.
I still want to know the configuration of your environment.
Thank you.

**Comment by yueqiw** [comment]
Hi, `requirements.txt` has been added to the repo. Sorry for the delay!
